services:
  api:
    image: zonda-api-dev
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: local
    container_name: zonda-api
    env_file: .env
    environment:
      USE_DEBUG_LOGGER: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: go.mod
          target: /go/src/myapp/go.mod
        - action: sync+restart
          path: .
          ignore:
            - .git
          target: /go/src/myapp
  db:
    image: mysql:8.0.28
    platform: linux/amd64 # linux/arm64/v8が存在しないため
    container_name: zonda-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
