services:
  api:
    image: zonda-api-dev
    build:
      context: .
      target: local
    container_name: zonda-api
    env_file: .env
    environment:
      USE_DEBUG_LOGGER: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/myapp
    depends_on:
      - db
  db:
    image: mysql:8.0.28
    platform: linux/amd64 # linux/arm64/v8が存在しないため
    container_name: zonda-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
