// Code generated by ogen, DO NOT EDIT.

package zondaapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CheckHealth implements checkHealth operation.
	//
	// GET /health
	CheckHealth(ctx context.Context) (*CheckHealthOK, error)
	// RefreshToken implements refreshToken operation.
	//
	// POST /refresh-token
	RefreshToken(ctx context.Context, req *RefreshTokenReq) (*RefreshTokenOK, error)
	// SignIn implements signIn operation.
	//
	// POST /sign-in
	SignIn(ctx context.Context, req *SignInReq) (*SignInOK, error)
	// SignUp implements signUp operation.
	//
	// POST /sign-up
	SignUp(ctx context.Context, req *SignUpReq) (*SignUpOK, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
