// Code generated by ogen, DO NOT EDIT.

package zondaapi

type CheckHealthOK struct {
	Revision string `json:"revision"`
}

// GetRevision returns the value of Revision.
func (s *CheckHealthOK) GetRevision() string {
	return s.Revision
}

// SetRevision sets the value of Revision.
func (s *CheckHealthOK) SetRevision(val string) {
	s.Revision = val
}
