// Code generated by ogen, DO NOT EDIT.

package zondaapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CheckHealthOperation OperationName = "CheckHealth"
	SignUpOperation      OperationName = "SignUp"
)
